package main

import (
	"fmt"
	"learn_code/algrithm/od/interview"
)

func main() {
	//od.TestSubstrLength()
	//od.TestBalancedStringSplit()
	//od.TestGetMinRobotEnergy()
	//od.TaxiBilling()
	//od.RichestLittleFamily()
	//od.OpenResourceHotSort()
	//od.AttendanceRecord()
	//od.DiffAbsOfHeight()
	//od.CoverMaxArea()
	//od.MaxWeightRemainSilver()
	//od.HotPageCount()
	//od.AbstractOfString()
	//od.SortedByLowestPosition()
	//od.ClearRepeatElem()
	//od.OrderOfStudents()
	//od.HeightAndWeightOrder()
	//od.ExchangeToMinStr()
	//od.GpuScheduleTime()
	//od.SumOfMaxAndMinN()
	//od.SearchPositionBinary()
	//od.MaxCountGems()
	//od.RsaEncode()
	//od.WordCountOfGrasp()
	//od.AssignCpuFromTwoGroups()
	//od.GetLuckyNumber()
	//od.GuestFromOtherCountry()
	//od.PathsOfVisited()
	//od.PrintWordMatchedWithInputPrefix()
	//od.PositionSmallestKAscii()
	//od.SpliceUrl()
	//od.ParkedCarsMinCount()
	//od.LoadBalanceApiCluster()
	//od.MaxDispatchTeamsCount()
	//od.SumOfContinuousInterval()
	//od.SplitAndTransferString()
	//od.ContinuousCharLength()
	//od.TransferAndCompulateExpress()
	//od.ComputeMaxReturns()
	//od.DrawingMachine()
	//od.AirportFlightScheduler()
	//od.Airs()
	//od.SearchGold()
	//od.HeightOfThreeTree()
	//examination.GamesOfABC()
	//interview.ArrangementString()
	//fmt.Println(interview.Top1Nums([]int{1, 2, 3, 2, 4, 2, 4, 4}))
	//fmt.Println(interview.IsConsecutiveSum(8))
	//fmt.Println(interview.AssignCandies([]int{2, 0, 1, 3, 4, 0, 2}))
	fmt.Println(interview.GetPrimeNumber(4))
}
