package main

import "learn_code/algrithm/od"

func main() {
	//od.TestSubstrLength()
	//od.TestBalancedStringSplit()
	//od.TestGetMinRobotEnergy()
	//od.TaxiBilling()
	//od.RichestLittleFamily()
	//od.OpenResourceHotSort()
	//od.AttendanceRecord()
	//od.DiffAbsOfHeight()
	//od.CoverMaxArea()
	//od.MaxWeightRemainSilver()
	//od.HotPageCount()
	//od.AbstractOfString()
	//od.SortedByLowestPosition()
	//od.ClearRepeatElem()
	//od.OrderOfStudents()
	//od.HeightAndWeightOrder()
	//od.ExchangeToMinStr()
	//od.GpuScheduleTime()
	//od.SumOfMaxAndMinN()
	//od.SearchPositionBinary()
	//od.MaxCountGems()
	//od.RsaEncode()
	//od.WordCountOfGrasp()
	//od.AssignCpuFromTwoGroups()
	//od.GetLuckyNumber()
	//od.GuestFromOtherCountry()
	//od.PathsOfVisited()
	//od.PrintWordMatchedWithInputPrefix()
	//od.PositionSmallestKAscii()
	//od.SpliceUrl()
	//od.ParkedCarsMinCount()
	//od.LoadBalanceApiCluster()
	//od.MaxDispatchTeamsCount()
	//od.SumOfContinuousInterval()
	//od.SplitAndTransferString()
	//od.ContinuousCharLength()
	//od.TransferAndCompulateExpress()
	//od.AirportFlightScheduler()
	od.Airs()
}
